Mission05_kizyy/Models/GradeForm.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mission05_kizyy.Models
{
    public class GradeForm
    {
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Assignments { get; set; }

        [Range(0, 100, ErrorMessage = "Group Project score must be between 0 and 100")]
        public int GroupProject { get; set; }

        [Range(0, 100, ErrorMessage = "Quizzes score must be between 0 and 100")]
        public int Quizzes { get; set; }

        [Range(0, 100, ErrorMessage = "Midterm Exam score must be between 0 and 100")]
        public int MidtermExam { get; set; }

        [Range(0, 100, ErrorMessage = "Final Exam score must be between 0 and 100")]
        public int FinalExam { get; set; }

        [Range(0, 100, ErrorMessage = "Intex score must be between 0 and 100")]
        public int Intex { get; set; }
    }
}

Mission05_kizyy/Controllers/FirstViewController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace Mission05_kizyy.Controllers
{
    public class FirstViewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult gradeCalculator ()
        {
            return View();
        }
    }

    public class FormData
    {
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Assignments { get; set; }

        [Range(0, 100, ErrorMessage = "Group Project score must be between 0 and 100")]
        public int GroupProject { get; set; }

        [Range(0, 100, ErrorMessage = "Quizzes score must be between 0 and 100")]
        public int Quizzes { get; set; }

        [Range(0, 100, ErrorMessage = "Midterm Exam score must be between 0 and 100")]
        public int MidtermExam { get; set; }

        [Range(0, 100, ErrorMessage = "Final Exam score must be between 0 and 100")]
        public int FinalExam { get; set; }

        [Range(0, 100, ErrorMessage = "Intex score must be between 0 and 100")]
        public int Intex { get; set; }
    }
}

Mission05_kizyy/Views/FirstView/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mission 4 - Assignment";
}

    <!--page title-->
    <h1 class="pinkfont">Mission 4 - Assignment</h1>
    <!--image-->
    <div class="background-image">
        <div class="transparent-background">
            <img src="img/kizy.jpeg" width="350" height="450" />
            <br />
        </div>
    </div>
    <!--text about things I want to learn from IS 413-->
    <h3 class="pinkfont">What I Hope to Get out of IS 413 Class</h3>
    <p>
        In a C# class, I hope to gain a solid understanding of the fundamentals of the language, including syntax, data types, variables, control structures, and object-oriented programming concepts.<br />
        I also want to learn how to write efficient and readable code, as well as how to debug and troubleshoot issues.<br />
        Additionally, I am interested in learning how to use C# to build applications, and I hope to get hands-on experience with real-world projects.
    </p>

    <!--list of top 3 jobs-->
    <h3 class="pinkfont">Top #3 Jobs I'm Interested</h3>
    <ul>
        <li>Data Science</li>
        <li>Software Engineer</li>
        <li>Data Analytics</li>
    </ul>

Mission05_kizyy/Views/FirstView/gradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!--form to input scores-->
<form>
    <h3 class="pinkfont">Grade Calculator</h3>
    <div style="display: flex;">
        <div style="width: 50%;">
            <label for="" style="margin-bottom:8px;"></label><br />
            <label for="assignments" style="margin-bottom:8px;">Assignments:</label><br />
            <label for="groupProject" style="margin-bottom:8px;">Group Project:</label><br />
            <label for="quizzes" style="margin-bottom:8px;">Quizzes:</label><br />
            <label for="midtermExam" style="margin-bottom:8px;">Midterm Exam:</label><br />
            <label for="finalExam" style="margin-bottom:8px;">Final Exams:</label><br />
            <label for="intex" style="margin-bottom:8px;">Intex:</label><br />
        </div>
        <div style="width: 25%;">
            <label style="font-size: smaller;">Score</label><br />
            <input type="text" id="assignments" name="assignments" style="width: 90%;" /><br />
            <input type="text" id="groupProject" name="groupProject" style="width: 90%;" /><br />
            <input type="text" id="quizzes" name="quizzes" style="width: 90%;" /><br />
            <input type="text" id="midtermExam" name="midtermExam" style="width: 90%;" /><br />
            <input type="text" id="finalExam" name="finalExam" style="width: 90%;" /><br />
            <input type="text" id="intex" name="intex" style="width: 90%;" /><br />

        </div>
    </div>
    <br />
    <input type="button" id="btnsubm" value="Calculate Grade" />
    <br /><br />
    <span id="result"></span>
</form>

Mission05_kizyy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <meta name="author" content="Kizy Matzenbacher">
    @*Icon Image*@
    <link rel="icon" type="image/x-icon" href="~/img/icon.png">
    @*Root Links*@
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/default.css" rel="stylesheet">
</head>
<body class="custom-background">
    @*Navbar*@
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" asp-controller="FirstView" asp-action="Index">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="FirstView" asp-action="gradeCalculator">Grade Calculator</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container my-5">
        @RenderBody()
    </div>

    <footer class="bg-light py-3">
        Copyright © Kizy Matzenbacher 2023. All rights reserved.
    </footer>

    @*js Links*@
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/js/gradeCalculator.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

</body>
</html>